Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  # Set vagrant machine name
  config.vm.define "linux-dev"

  # config.vm.provider :virtualbox do |vb|
  config.vm.provider "vmware_desktop" do |vb|
    # Set virtualbox machine name
    vb.name = "linux-dev"
  end

  # Set linux host name
  config.vm.hostname = "linux-dev"
  config.vm.synced_folder ENV["MOUNT_PATH"], "/home/vagrant/mount"

  # This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Only allow access via localhost
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device
  # config.vm.network "public_network"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
